vpc_cidr_block    = "10.0.0.0/16"
subnet_cidr_block = "10.0.10.0/24"
avail_zone        = "us-east-1a"
avail_zone2        = "us-east-1b"
avail_zone3        = "us-east-1c"
env_prefix        = "dev"
instance_type     = "t2.micro"